### ISSUE TITLE
Transfer tiran/instructlab-quantize to instructlab org

### ISSUE THREAD

**Issue by tiran** [instructlab/dev-docs#53]
I would like to transfer https://github.com/tiran/instructlab-quantize from my personal account to the instructlab organization. The repository contains a new package with pre-build binaries for InstructLab CLI. You can find more information in the ticket https://github.com/instructlab/instructlab/issues/438 and pull request https://github.com/instructlab/instructlab/pull/1017 .

## TODO

- [x] transfer repository from my personal account to instructlab
- [ ] update URLs in pyproject.toml
- [ ] add boiler plate to repository
   - CoC
   - SECURITY.md
   - mergify rules
- [x] configure branch protection
- [ ] change trusted publisher settings in PyPI
- [ ] change trusted publisher settings in Test PyPI

**Comment by russellb** [comment]
@instructlab/oversight-committee FYI -- we have a request for a new repo here. I think it makes sense.

**Comment by jjasghar** [comment]
I agree, thank you for offering to move it over @tiran !

**Comment by mairin** [comment]
ack +1 as committee member

**Comment by danmcp** [comment]
+1 from me as well

**Comment by russellb** [comment]
I think we can proceed here.  @tiran if you initiative the transfer, I'll accept it to complete step 1.

**Comment by russellb** [comment]
> @russellb I have insufficient permission to transfer ownership to InstructLab. I need "create repo" permission for the transfer.

or maybe you could add me as an admin collaborator on the repo and I can move it?

**Comment by tiran** [comment]
You are now a collaborator. However GH does not give me the dropdown to make you an admin. I'll look into the matter tomorrow.

**Comment by russellb** [comment]
> You are now a collaborator. However GH does not give me the dropdown to make you an admin. I'll look into the matter tomorrow.

OK. If we can catch each other on Slack at the same time we can work it out.  I may just need to give you elevated perms on the instructlab org temporarily to make it easy.

**Comment by nathan-weinberg** [comment]
Can we close this?

**Comment by russellb** [comment]
> Can we close this?

if someone goes through the checklist and verifies that they can be checked off :)

**Comment by nathan-weinberg** [comment]
@russellb i went through the list - checked off a few things but still some pending tasks to be done

**Comment by nathan-weinberg** [comment]
No one seems to be working on this, so I'm closing it.
